name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Release
        run: cargo build --release
        
      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/oxidroid
            target/release/oxidroid.exe
          fail_on_unmatched_files: false